---
title: "Infographic"
author: "Helena Parsons"
format: pdf
date: "2026-06-04"
---

# 1. Loading packages

```{r}
#| label: loading-packages
#| warning: false

# loading neccessary packages
library(tidyverse)
library(ggridges)
library(here)
library(corrplot)
library(showtext)
library(ggimage)
```

# 2. Adding custom fonts and loading ggplot2

```{r}
#| label: loading-font-adding-ggplot2

# choosing font from google library
font_add_google("EB Garamond", "garamond")
# ensures text will be automatically rendered on new devices
showtext_auto()

# loading ggplot2 library
library(ggplot2)
```

#
# 3. Visualizations

## 3a. Visualization #1: Scatterplot

### Reading data

```{r}
#| label: reading-data

# creating new object
job_search <- 
  # reading csv from data file
  read_csv(
    # directing function to data file
    here("data", 
         # csv: personal-data
         "personal-data.csv"))
```

### Creating plot

```{r}
#| label: first-visualization

# base layer: ggplot
ggplot(
  # df: job_search
  data = job_search,
  # x-axis : time spent on outside engagements
  # y-axis : time spent on job search
  mapping = aes(x = outside_eng,
                                      y = job_search)) +
  # first layer: scatterplot
  geom_point(color = "turquoise4",
              size = 3) +
  # changing title and axes' titles
  labs(title = "Affect of outside engagements on job search",
       x = "Time spent at work or school (hours)",
       y = "Time spent on job search (min)") +
  # customizing theme
  theme_linedraw() +
  # customizing font
  theme(text = element_text(family = "garamond")) +
  # getting rid of gridlines
  theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())
```

## 3b. Visualization #2: Ridgeline plot

### Wrangling data
```{r}
#| label: wrangling-data-for-ridgeline

# creating new object
job_search_clean <- 
  # df: job_search
  job_search |>
  # mutating data
  mutate(
    # changing values to be words in stress column
    stress = case_when (
    stress == "0" ~ "Zero",
    stress == "1" ~ "One",
    stress == "2" ~ "Two",
    stress == "3" ~ "Three",
    stress == "4" ~ "Four",
    stress == "5" ~ "Five"))

```

### Creating plot

```{r}
#| label: second-visualization

# base layer: ggplot
ggplot(
  # df: job_search_clean
  data = job_search_clean,
  # x-axis: time spent on job search
  # y-axis: level of stress
  # filling by x-axis value
       mapping = aes(x = job_search,
                     y = stress,
                     fill = after_stat(x))) +
  # first layer: ridgeline plot
  geom_density_ridges_gradient() +
  # coloring ridgeline by gradient corresponding to x-axis value
     scale_fill_viridis_c(option = "turbo", name = "Minutes") +
  # changing title and axes' titles
  labs(title = "Job search differs by level of stress",
       x = "Time spent on job search (minutes)",
       y = "Level of stress"
       ) +
  # changing theme
  theme_linedraw() +
  # changing font
  theme(text = element_text(family = "garamond")) +
  # getting rid of gridlines
  theme(panel.grid.major = element_blank(),
         panel.grid.minor = element_blank())
```

## 3c. Visualization #3: Correlogram

### Wrangling data
```{r}
#| label: wrangling-data-for-correlogram

# creating new object
job_search_corr <- 
  # df: job_search
  job_search |>
  # getting rid of date column
  select(job_search, outside_eng, stress, sleep, social_media, day_to_grad)
# changing names of columns 
names(job_search_corr) <- c("Job search", "Outside engagements", "Stress", "Sleep", "Social media usage", "Days till graduation")
```

### Creating plot

```{r}

```

